# https://dbml.dbdiagram.io/docs/

Table Users {
  id integer [primary key, increment]
  username varchar(150) [unique, not null]
  email varchar [unique, not null]
  password varchar [not null]
  first_name varchar(50)
  last_name varchar(50)
}

Table Posts {
  id integer [primary key, increment]
  user_id integer [ref: > Users.id, not null]
  content text [not null]
  created_at datetime
  updated_at datetime
}